if NetworkAccountSTEAM then
function NetworkAccountSTEAM:username_id() return

--> CHOISISSEZ VOTRE PSEUDO FAKE ENTRE LES GUILLEMETS:

"ULTIMATE USER"

--> SUPPRIMEZ CE FICHIER SI VOUS VOULEZ DESACTIVER PSEUDO CHANGER.

end end PSEUDO_CHANGER = 0